### ISSUE TITLE
Fish B & C Not Appearing

### ISSUE THREAD

**Issue by johnny-la** [FeedJonathanFoundation/ubisoft-game-lab#153]
Fish B & C's meshes are missing, and thus the fish can't be seen on-screen.

![fishnotappearing](https://cloud.githubusercontent.com/assets/10332234/13918768/ad3c2986-ef3f-11e5-868a-899acc8a404a.png)

**Comment by stellarxo** [comment]
@johnny-la I tried repushing the prefabs - did this solve it?

**Comment by stellarxo** [comment]
Issue: files are .mb and can only be seen on machines with Maya installed.

Solutions: download Maya or re-export
