### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by mjholtzem** [FeedJonathanFoundation/ubisoft-game-lab#402]
You guys should add a license to this repository. Or specify in the readme what usage restrictions there are on the code and art assets

**Comment by johnny-la** [comment]
We chose default copyright restrictions for the project:

![image](https://cloud.githubusercontent.com/assets/10332234/25583746/298df742-2e61-11e7-988b-04a18712ac03.png)
https://help.github.com/articles/licensing-a-repository/
