### ISSUE TITLE
LightCube Crash

### ISSUE THREAD

**Issue by stellarxo** [FeedJonathanFoundation/ubisoft-game-lab#50]
When LightCube(absorbable) are absorbed, it crashes the program

![screen shot 2016-02-18 at 9 22 21 pm](https://cloud.githubusercontent.com/assets/11700445/13181706/583702ae-d6fc-11e5-9139-fc1e53006584.png)

**Comment by johnny-la** [comment]
What script causes that error? The most probable cause of error is the following:

* `AbstractFish` holds a reference to another fish. When the fish is killed, the fish's `GameObject` is destroyed, and the `AbstractFish` still holds a reference to the destroyed fish's `Rigidbody`, httries to which no longer exists

In any case, what's happening is that a script is holding a reference to a destroyed `GameObject`'s Rigidbody, which is causing a `MissingComponentException`

**Comment by alisterdev** [comment]
Bump the bug

**Comment by alisterdev** [comment]
@johnny-la @stellarxo I believe if was my fuck up in LightEnergy.cs I believe it is fixed in my new PR
