### ISSUE TITLE
Fish disappear when player is chasing

### ISSUE THREAD

**Issue by stellarxo** [FeedJonathanFoundation/ubisoft-game-lab#81]
I'm assuming that the player disable collider is calling the OnTriggerExit function of the SpawnVolume, making all the fish disappear
Possible fixes are to expand the disable collider and/or spawn volume, but this won't account for when fish swim far from their point of origin
Prevent spawn volume from disabling fish if they are in sight of the player

**Comment by alisterdev** [comment]
+1

**Comment by alisterdev** [comment]
@stellarxo Solved?
